const {test}=require('node:test');const assert=require('node:assert/strict');const Night=require('./engine');
function advance(n,seconds){for(let t=0;t<seconds;t+=.05)n.tick(.05);}
test('Open door allows Aksel to attack on both routes',()=>{for(const rng of [()=>.1,()=>.9]){const n=new Night(1,rng);advance(n,90);assert.equal(n.status,'lost');assert.ok(n.events.includes('scare'));}});
test('Correct door repels Aksel; wrong door does not',()=>{for(let side=0;side<2;side++){let n=new Night();n.position=3;n.side=side;n.doors[side]=true;advance(n,2);assert.equal(n.position,0);assert.ok(n.events.includes('knock'));n=new Night();n.position=3;n.side=side;n.doors[1-side]=true;advance(n,6);assert.equal(n.status,'lost');}});
test('Doors, lights, and monitor draw additional power',()=>{let a=new Night(),b=new Night();b.toggle('doors',0);b.toggle('lights',1);b.toggle('monitor');advance(a,5);advance(b,5);assert.ok(b.power<a.power);assert.equal(b.usage,5);});
test('Blackout opens doors and disables all electrical controls',()=>{const n=new Night();n.power=.001;n.doors=[true,true];n.lights=[true,true];n.monitor=true;n.tick(.1);assert.equal(n.power,0);assert.deepEqual(n.doors,[false,false]);assert.deepEqual(n.lights,[false,false]);assert.equal(n.monitor,false);n.toggle('doors',0);assert.equal(n.doors[0],false);advance(n,10);assert.equal(n.status,'lost');});
test('Every night is winnable using cameras and timed doors',()=>{for(let level=1;level<=5;level++){const n=new Night(level,()=>.4);n.monitor=true;for(let i=0;i<5000&&n.status==='playing';i++){n.doors=[false,false];if(n.position===3)n.doors[n.side]=true;n.tick(.05);}assert.equal(n.status,'won');assert.ok(n.power>0);}});
test('Camera location matches movement and route',()=>{const n=new Night();for(let side=0;side<2;side++){n.side=side;for(let p=0;p<=3;p++){n.position=p;assert.equal(n.room,[0,1,2+side,4+side][p]);}}});
test('Completed simulation cannot change',()=>{const n=new Night();n.time=239.99;n.tick(.02);const p=n.power;n.tick(10);n.toggle('doors',0);assert.equal(n.status,'won');assert.equal(n.power,p);assert.equal(n.doors[0],false);});
